--- #YAML:1.0
name:               Catalyst-Plugin-Data-Pensieve
version:            0.01
abstract:           Easy access to Data::Pensieve within Catalyst applications
author:
    - Michael Aquilina <aquilina@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Pensieve: 0
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4

